mod service_locator;
mod publishers_subscribers;
mod model_view_controller;
mod data_access_object;
mod intercepting_filter;
mod front_controller;
mod business_delegate;
mod composite_entity;
mod transfer_object;
